# Site settings
port: 4000
title: Experiments with py5
email: mamba2928@yahoo.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Here I will write about my experiments with py5 and numpy.
baseurl: "" # the subpath of your site, e.g. /blog
regenerate: true
url: "https://monkstone.github.io/py5-examples" # the base hostname & protocol for your site, e.g. http://example.com
urls:
  bugs: https://github.com/monkstone/py5-examples/issues
  github: https://github.com/monkstone/py5-examples
  wiki: https://github.com/monkstone/py5-examples/wiki
twitter_username: monkstoneT
github_username:  monkstone
theme: minima
syntax-highlighting:
  enabled: true

sass:
  sass_dir: _sass

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links
